### ISSUE TITLE
v10.3.1-2.3 deleted?

### ISSUE THREAD

**Issue by fpistm** [xpack-dev-tools/arm-none-eabi-gcc-xpack#17]
Hi @ilg-ul 
It seems the GH release v10.3.1-2.3 has been removed? Why?

**Comment by ilg-ul** [comment]
oops!

it was definitely a mistake, I'll fix it as soon as possible.

**Comment by ilg-ul** [comment]
It looks like I inadvertently pressed the wrong button and I re-published that release, which changed it to draft. :-(

I'm re-running the tests to be sure, but I guess it is ok now.

**Comment by fpistm** [comment]
Thanks for the quick answer and fix 👏 
Hope the sha256 is the same else the current release of the STM32 core will be deprecated.
I'm waiting user feedback about this.

**Comment by ilg-ul** [comment]
Normally the sha256 should be the same, my understanding is that only the draft flag was set, the rest of the content was preserved, anyway I did not have to actually re-load the files, they were there, but not visible.

**Comment by fpistm** [comment]
Ah OK. So it should be fine.
I close this issue. Thank you again 👍

**Comment by ilg-ul** [comment]
You're welcome!
