### ISSUE TITLE
update to Arm GNU Toolchain 11.2

### ISSUE THREAD

**Issue by dsm** [xpack-dev-tools/arm-none-eabi-gcc-xpack#19]
Hi,

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads 

this page says it's deprecated and use below linked and renamed GNU Arm Embedded Toolchain to Arm GNU Toolchain. 

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain is the new link for new toolchain and discontinued older embedded toolchain release.

Any progress for this ?

**Comment by ilg-ul** [comment]
@dsm, thank you for the update, I missed the Arm project restructuring.

I'll consider a new release soon.

**Comment by ilg-ul** [comment]
Done.

**Comment by dsm** [comment]
Thanks 😊
