### ISSUE TITLE
update Arm GCC 11.3.Rel1

### ISSUE THREAD

**Issue by dsm** [xpack-dev-tools/arm-none-eabi-gcc-xpack#22]
Arm GNU Toolchain
Version 11.3.Rel1

Released: August 8, 2022

**Comment by ilg-ul** [comment]
Thank you, I'll make a new release.

Do you know of any method to get notifications when Arm makes new releases?

**Comment by dsm** [comment]
Thanks, I don't know, I check manually but maybe using a CI script to parse the web site every day(maybe week) for new release

**Comment by dsm** [comment]
```javascript
var Xray = require('x-ray')
var x = Xray()
var url = 'https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads';


x(url, '.o-widget' ,'h2')(function(err, text) {
    var toolchain_name = text.trim()
    console.log(toolchain_name) 
    x(url, '.o-widget' ,'h4')(function(err, text) {
        var toolchain_version = text.trim()
        console.log(toolchain_version) 
        x(url, '.c-widget' ,'a')(function(err, text) {
            console.log(text.trim()) 
          })
      })
})
```


maybe you can use this code. code output like this

`Arm GNU Toolchain`
`Version 11.3.Rel1`
`Downloads: 11.3.Rel1 August 08, 2022`

**Comment by ilg-ul** [comment]
Yes, this might be a solution. Improve it to compare the string with a known one and fail the CI job if different, to trigger an email. And add the GitHub Action definition.

Ah, and could you use promises not callbacks?

**Comment by ilg-ul** [comment]
- <https://xpack.github.io/blog/2022/08/28/arm-none-eabi-gcc-v11-3-1-1-1-released/>

Please notify me on future Arm releases, since I don't monitor the Arm site.
