### ISSUE TITLE
12.3.Rel1

### ISSUE THREAD

**Issue by yyjdelete** [xpack-dev-tools/arm-none-eabi-gcc-xpack#31]
https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads/

**Comment by ilg-ul** [comment]
Thank you, I'll consider a new release.

**Comment by tw-ghub** [comment]
Thanks Liviu - I'd also be interested in a new release.

**Comment by ilg-ul** [comment]
Closed as completed.
