### ISSUE TITLE
Is the 32-bit windows version of the release missing

### ISSUE THREAD

**Issue by HalfSweet** [xpack-dev-tools/arm-none-eabi-gcc-xpack#37]
### Disclaimer

The xPack GNU Arm Embedded GCC is only a binary distribution of
the [Arm GNU Toolchain](https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain),
and does not intend to add new functionality, or to fix existing problems.

If you have questions/suggestions related to the procedure used to
build/publish the binary distribution, continue reading the next sections.

If you have problems related to Arm GCC functionality, please use the
official [Launchpad tracker](https://bugs.launchpad.net/gcc-arm-embedded/).

### Prerequisites

Before entering a new ticket, please consider the following:

- [x] read the documentation pages carefully (`share/doc/pdf/gcc/gcc.pdf`)
- [x] check the [xPack Forums](https://www.tapatalk.com/groups/xpack/) for similar problems
- [x] check the [GitHub Issues](https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/issues/)

If you still could not find an answer, if you have interesting use
cases, if you have custom configurations, and generally if you have
any experience that you would like to share with others, use the
[xPack Forums](https://www.tapatalk.com/groups/xpack/), the
GNU Arm Embedded GCC section.

If you are convinced that you identified a bug related to the binary
distribution, not to GNU Arm Embedded GCC itself (if you have doubts,
use the forum), or you have a pertinent suggestion how to enhance the
xPack GNU Arm Embedded GCC distribution, continue and register a new issue.

### Test with the original Arm GNU Toolchain distribution

Run your build with the original [Arm GNU Toolchain](https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain) distribution.

If the problem is still there, report the issue to Arm.

If the problem does not occur with the original Arm toolchain, but occur
with the xPack toolchain, proceed and report it here.

### Description

I didn't find any pre-built files for the most recent release version of 32-bit windows inside releases.
Will it be added in later releases, or is there some reason we no longer support 32-bit windows?

### Versions

- 13.3.1-1.1

---

**Comment by ilg-ul** [comment]
> I didn't find any pre-built files for the most recent release version of 32-bit windows
> Will it be added in later releases, 

No, support for 32-bit Windows and Linux was removed in 2022.

> or is there some reason we no longer support 32-bit windows?

Microsoft removed support for 32-bit Windows in 2020.
